FROM node:14.15.4 as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build
RUN cd build && npm ci --production
CMD [ "npm", "start"]

# Added ace commands
RUN cd build && ENV_PATH=.env.production node ace migration:run

# production environment
# FROM nginx:stable-alpine
# COPY --from=build /app/build /usr/share/nginx/html
# # copy nginx config
# COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]